#!/bin/bash

function pipe() {
  while true; do
    read line < ".fifos/$1-w"
    cmds=($line)
    dest=${cmds[0]}
    msg=${cmds[1]}
    if [ -p ".fifos/$dest-r" ]; then
      echo "$1 $msg" > ".fifos/$dest-r"
    fi
  done
}

# Allocate channels
mkdir -p .fifos
rm .fifos/* &> /dev/null

for script in "$@"; do
  mkfifo ".fifos/$script-r"
  mkfifo ".fifos/$script-w"
done

# Initialize packages
inits=""
for script in "$@"; do
  cat ".fifos/$script-w" > /dev/null &
  inits="$inits $!"
done

for script in "$@"; do
  "./$script" ".fifos/$script-r" ".fifos/$script-w" &
done

echo "init"
for init in $inits; do
  wait $init
done
echo "inited"

# Subscribe to packages and run them
for script in "$@"; do
  pipe "$script" &
  echo "readying"
  echo "ready" > ".fifos/$script-r"
done

wait

